#Script to deploy on Render cloud platform

name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} 
        service-id: "https://api.render.com/deploy/srv-cg9dcvseooghng7li3i0?key=A2CNu81HeVI"
        retries: 20
        wait: 16000
        sleep: 3000
